import 'package:pixura_ai/core/theme/app_colors.dart';
import 'package:pixura_ai/core/theme/app_theme_extension.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class AppTheme {
  static final ThemeData lightTheme = ThemeData(
    fontFamily: 'General Sans',
    canvasColor: AppColors.foggy,
    scaffoldBackgroundColor: AppColors.foggy,
    useMaterial3: true,
    brightness: Brightness.light,
    cardColor: AppColors.shade100,
    appBarTheme: const AppBarTheme(backgroundColor: AppColors.foggy),
    dialogTheme: DialogThemeData(
      backgroundColor: AppColors.shade100,
      surfaceTintColor: Colors.transparent,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16.r)),
    ),
    bottomSheetTheme: BottomSheetThemeData(
      backgroundColor: AppColors.shade100,
      surfaceTintColor: Colors.transparent,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20.r)),
      ),
    ),
    colorScheme: const ColorScheme.light(
      primary: AppColors.purple,
      onPrimary: AppColors.shade100,
      secondary: AppColors.shade600,
      surface: AppColors.shade200,
      onSurface: AppColors.shade800,
      inversePrimary: AppColors.lavender,
      tertiary: AppColors.shade600,
      onTertiary: AppColors.shade900,
    ),
    extensions: <ThemeExtension<dynamic>>[
      AppColorsExtension(
        greySolid: AppColors.shade600,
        grey200: AppColors.shade200,
        grey100: AppColors.shade100,
        grey: AppColors.shade500,
        lightGrey: AppColors.shade300,
        backgroundColor: AppColors.foggy,
        componentBackgroundColor: AppColors.shade100,
        secondaryBlack: AppColors.shade800,
        primaryTextColor: AppColors.shade900,
        secondaryTextColor: AppColors.shade600,
        blue300: AppColors.skies,
        blue400: AppColors.cyan,
        switchActiveTrack: AppColors.purple,
        switchInactiveTrack: AppColors.shade400,
        switchThumb: AppColors.shade100,
        selectionHighlight: AppColors.lemon,
        selectionHighlightText: AppColors.shade900,
        successBackground: AppColors.lightGreen,
        successForeground: const Color(0xFF10B981),
        successBorder: AppColors.mint,
        warningBackground: AppColors.mustard,
        warningForeground: const Color(0xFFF59E0B),
        infoBackground: AppColors.cyan,
        infoBorder: AppColors.skies,
        infoColor: const Color(0xFF3B82F6),
        iconBackgroundYellow: AppColors.olive,
        statusScheduledColor: const Color(0xFFF59E0B),
        statusScheduledBg: AppColors.mustard,
        statusInProgressColor: const Color(0xFF3B82F6),
        statusInProgressBg: AppColors.cyan,
        statusCompletedColor: const Color(0xFF10B981),
        statusCompletedBg: AppColors.lightGreen,
        statusDelayedColor: const Color(0xFFEF4444),
        statusDelayedBg: AppColors.rose,
        statusCancelledColor: AppColors.shade600,
        statusCancelledBg: AppColors.shade200,
        gradientOrangeStart: const Color(0xFFFE9A00),
        gradientOrangeEnd: const Color(0xFFFF6900),
        fieldLogBrown: const Color(0xFF92400E),
        jobStatusOrange: const Color(0xFFF97316),
      ),
    ],
    textTheme: TextTheme(
      displayLarge: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 26.sp,
        fontWeight: FontWeight.bold,
        color: AppColors.shade900,
      ),
      displayMedium: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 22.sp,
        fontWeight: FontWeight.w600,
        color: AppColors.shade900,
      ),
      displaySmall: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 20.sp,
        fontWeight: FontWeight.w600,
        color: AppColors.shade900,
      ),
      headlineLarge: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 18.sp,
        fontWeight: FontWeight.bold,
        color: AppColors.shade900,
      ),
      headlineMedium: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 16.sp,
        fontWeight: FontWeight.w500,
        color: AppColors.shade900,
      ),
      headlineSmall: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 14.sp,
        fontWeight: FontWeight.w400,
        color: AppColors.shade700,
      ),
      titleLarge: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 16.sp,
        fontWeight: FontWeight.w600,
        color: AppColors.shade800,
      ),
      titleMedium: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 14.sp,
        fontWeight: FontWeight.w500,
        color: AppColors.shade700,
      ),
      titleSmall: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 12.sp,
        fontWeight: FontWeight.w400,
        color: AppColors.shade600,
      ),
      labelLarge: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 14.sp,
        fontWeight: FontWeight.w600,
        color: AppColors.shade900,
      ),
      labelMedium: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 12.sp,
        fontWeight: FontWeight.w500,
        color: AppColors.shade900,
      ),
      labelSmall: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 11.sp,
        fontWeight: FontWeight.w400,
        color: AppColors.shade900,
      ),
      bodyLarge: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 16.sp,
        fontWeight: FontWeight.w500,
        color: AppColors.shade800,
      ),
      bodyMedium: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 14.sp,
        fontWeight: FontWeight.w400,
        color: AppColors.shade700,
      ),
      bodySmall: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 12.sp,
        fontWeight: FontWeight.w400,
        color: AppColors.shade600,
      ),
    ),
  );
  static final ThemeData darkTheme = ThemeData(
    fontFamily: 'General Sans',
    useMaterial3: true,
    scaffoldBackgroundColor: AppColors.shade900,
    colorScheme: const ColorScheme.dark(
      primary: AppColors.purple,
      onPrimary: AppColors.shade100,
      secondary: AppColors.shade800,
      surface: AppColors.shade800,
      inversePrimary: AppColors.shade800,
      onSurface: AppColors.shade100,
      tertiary: AppColors.shade600,
      onTertiary: AppColors.shade100,
    ),
    brightness: Brightness.dark,
    cardColor: AppColors.shade800,
    appBarTheme: const AppBarTheme(backgroundColor: AppColors.shade900),
    dialogTheme: DialogThemeData(
      backgroundColor: AppColors.shade800,
      surfaceTintColor: Colors.transparent,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16.r)),
    ),
    bottomSheetTheme: BottomSheetThemeData(
      backgroundColor: AppColors.shade800,
      surfaceTintColor: Colors.transparent,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20.r)),
      ),
    ),
    extensions: <ThemeExtension<dynamic>>[
      AppColorsExtension(
        greySolid: AppColors.shade400,
        grey200: AppColors.shade800,
        grey100: AppColors.shade700,
        grey: AppColors.shade600,
        lightGrey: AppColors.shade700,
        backgroundColor: AppColors.shade900,
        componentBackgroundColor: AppColors.shade800,
        secondaryBlack: AppColors.shade100,
        primaryTextColor: AppColors.shade100,
        secondaryTextColor: AppColors.shade500,
        blue300: AppColors.shade400,
        blue400: AppColors.shade500,
        switchActiveTrack: AppColors.purple,
        switchInactiveTrack: AppColors.shade700,
        switchThumb: AppColors.shade100,
        selectionHighlight: AppColors.lemon,
        selectionHighlightText: AppColors.shade900,
        successBackground: const Color(0xFF064E3B),
        successForeground: const Color(0xFF10B981),
        successBorder: const Color(0xFF1A5A3A),
        warningBackground: const Color(0xFF92400E),
        warningForeground: const Color(0xFFF59E0B),
        infoBackground: const Color(0xFF1E3A5F),
        infoBorder: const Color(0xFF2E5A8F),
        infoColor: const Color(0xFF64B5F6),
        iconBackgroundYellow: const Color(0xFF4A4020),
        statusScheduledColor: const Color(0xFFF59E0B),
        statusScheduledBg: const Color(0xFF4A3F1A),
        statusInProgressColor: const Color(0xFF64B5F6),
        statusInProgressBg: const Color(0xFF1E3A5F),
        statusCompletedColor: const Color(0xFF10B981),
        statusCompletedBg: const Color(0xFF1A3A2A),
        statusDelayedColor: const Color(0xFFEF5350),
        statusDelayedBg: const Color(0xFF4A1A1A),
        statusCancelledColor: const Color(0xFFBDBDBD),
        statusCancelledBg: const Color(0xFF2A2A2A),
        gradientOrangeStart: const Color(0xFFFE9A00),
        gradientOrangeEnd: const Color(0xFFFF6900),
        fieldLogBrown: const Color(0xFFBCAAA4),
        jobStatusOrange: const Color(0xFFFF9800),
      ),
    ],
    textTheme: TextTheme(
      displayLarge: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 26.sp,
        fontWeight: FontWeight.bold,
        color: AppColors.shade100,
      ),
      displayMedium: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 22.sp,
        fontWeight: FontWeight.w600,
        color: AppColors.shade100,
      ),
      displaySmall: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 20.sp,
        fontWeight: FontWeight.w600,
        color: AppColors.shade100,
      ),
      headlineLarge: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 18.sp,
        fontWeight: FontWeight.bold,
        color: AppColors.shade100,
      ),
      headlineMedium: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 16.sp,
        fontWeight: FontWeight.w500,
        color: AppColors.shade100,
      ),
      headlineSmall: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 14.sp,
        fontWeight: FontWeight.w400,
        color: AppColors.shade100,
      ),
      titleLarge: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 16.sp,
        fontWeight: FontWeight.w600,
        color: AppColors.shade100,
      ),
      titleMedium: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 14.sp,
        fontWeight: FontWeight.w500,
        color: AppColors.shade100,
      ),
      titleSmall: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 12.sp,
        fontWeight: FontWeight.w400,
        color: AppColors.shade100,
      ),
      labelLarge: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 14.sp,
        fontWeight: FontWeight.w600,
        color: AppColors.shade100,
      ),
      labelMedium: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 12.sp,
        fontWeight: FontWeight.w500,
        color: AppColors.shade100,
      ),
      labelSmall: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 11.sp,
        fontWeight: FontWeight.w400,
        color: AppColors.shade100,
      ),
      bodyLarge: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 16.sp,
        fontWeight: FontWeight.w500,
        color: AppColors.shade100,
      ),
      bodyMedium: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 14.sp,
        fontWeight: FontWeight.w400,
        color: AppColors.shade100,
      ),
      bodySmall: TextStyle(
        fontFamily: 'General Sans',
        fontSize: 12.sp,
        fontWeight: FontWeight.w400,
        color: AppColors.shade100,
      ),
    ),
  );
}
